require_relative '../interpreter'
require_relative '../lib/reader'
require_relative '../lib/translator'
require_relative '../lib/dictionary'
require_relative '../lib/grammar'
require_relative '../lib/sentence'
require_relative '../lib/subject'
